project:
  type: website
  output-dir: docs

lang: pl

website:
  title: "PODSTAWY METODOLOGII I STATYSTYKI - ĆWICZENIA"
  navbar:
    pinned: true
    logo: swpslogo/uniwersytet-swps_wheel_bt.png
    left:
      - href: index.qmd
        text: Wprowadzenie
        

      - text: Zajęcia
        menu:
          - href: Cwiczenia/start.qmd
            text: "0. START | Instalacja i pierwsze uruchomienie SPSS"
          - href: Cwiczenia/SPSS.qmd
            text: "1. Wprowadzenie do SPSS | Tworzenie baz danych | Podstawowe operacje na danych | Tworzenie wskaźników zmiennych"
          - href: Cwiczenia/Statystyki_opisowe.qmd
            text: "2. Statystyki opisowe zmiennych | Rozkład normalny | Testy normalności rozkładu"
          - href: Cwiczenia/Analiza_korelacji.qmd
            text: "3. Analiza korelacji | Zasady wyboru współczynnika korelacji | Współczynnik determinacji | Analiza kontyngencji"          
          - href: Cwiczenia/Niezalezne.qmd
            text: "4. Parametryczne i nieparametryczne testy różnic dla prób niezależnych: test t dla prób niezależnych, test U Manna-Whitneya"
          - href: Cwiczenia/Zalezne.qmd
            text: "5. Parametryczne i nieparametryczne testy różnic dla prób zależnych: test t dla prób zależnych, test Wilcoxona. Test t dla jednej próby."
          - href: Cwiczenia/Podsumowanie.qmd
            text: "6. Podsumowanie analiz poznanych podczas ćwiczeń i kolokwium semestralne."
      - href: Zadania.qmd
        text: Zadania
      - href: Sylabus.qmd
        text: Sylabus
  page-navigation: true
  search: true

format:
  html:
    theme:
      light: cosmo
      dark: sandstone
    toggle: true
    css: assets/styles.css
    toc: true
    toc-location: left







